master:
  image: blacklabelops/jenkins:alpine
  ports:
    - 8090:8080
  expose:
    - 50000
    - 8080
  volumes:
    - /jenkins
  environment:
    - 'JAVA_VM_PARAMETERS=-Xmx512m -Xms256m'
    - 'JENKINS_ADMIN_USER=jenkins'
    - 'JENKINS_ADMIN_PASSWORD=swordfish'
    - 'JENKINS_MASTER_EXECUTORS=0'
    - 'JENKINS_PLUGINS=swarm git'
    - 'JENKINS_SLAVEPORT=50000'

slave1:
  image: csanchez/jenkins-swarm-slave
  hostname: slave1
  command: -master http://master:8080 -username jenkins -password jenkins -executors 2 -labels "LabTIC Win7_32b"
  links:
    - master

slave2:
  image: csanchez/jenkins-swarm-slave
  hostname: slave2
  command: -master http://master:8080 -username jenkins -password jenkins -executors 2 -labels "LabTIC Win7_64b"
  links:
    - master
